# Generated by Django 4.1.1 on 2022-09-10 20:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_emergencycontacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmergencyContacts',
            new_name='EmergencyContact',
        ),
    ]
