# Generated by Django 4.1.1 on 2022-09-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_emergencycontacts_emergencycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
