# Generated by Django 3.2.5 on 2023-01-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230108_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.TextField(),
        ),
    ]
