# Generated by Django 3.2.5 on 2023-01-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230108_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.TextField(null=True),
        ),
    ]
