# Generated by Django 3.2.5 on 2023-01-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230113_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.TextField(null=True),
        ),
    ]
